### ISSUE TITLE
capturar win e loss de um ID

### ISSUE THREAD

**Issue by int211** [iago-silva/bot-iqoption-mhi#1]
Existe como capturar percentual de win e loss via api ou qualquer outro ?
Obrigado e parabens pelo trabalho!

**Comment by iago-silva** [comment]
Pela API eu acredito que não (não tenho certeza), mas você pode fazer o cálculo...

porcentagem_wins = wins * 100 / mhi_count
porcentagem_losses = 100 - porcentagem_wins

**Comment by int211** [comment]
Opa, isso pra qualquer ID ?

**Comment by iago-silva** [comment]
Não entendi...
