### ISSUE TITLE
Não entrar contra microtendência

### ISSUE THREAD

**Issue by BernardoCR** [iago-silva/bot-iqoption-mhi#2]
Iago, parabéns pelo código. É show de bola.
Queria te pedir uma coisa, tem como fazer com que o robô pegue as últimas 6 velas e se não houver nenhuma vela vermelha, ou nenhuma verde, ele não faça a entrada por estar em uma microtendência?
Isso evitaria alguns loss.

Valeu!

**Comment by iago-silva** [comment]
Isso poderia ser feito facilmente.

- Pegar as primeiras 6 velas ao invés de 3
- Verificar se as 6 velas são de cores diferentes
    - Se sim: continua o MHI com as 3 primeiras velas
    - Se não: aborta a operação

Não vou implementar isso no bot porque o objetivo dele é só dar a base do MHI

**Comment by BernardoCR** [comment]
Consegui. Valeu!
